# Generated by Django 4.0.4 on 2024-06-04 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=200)),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('price', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('sqft', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('booked', models.BooleanField(default=False)),
                ('main_image', models.ImageField(upload_to='photos/')),
                ('image_1', models.ImageField(upload_to='photos/')),
                ('image_2', models.ImageField(upload_to='photos/')),
                ('image_3', models.ImageField(upload_to='photos/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
