# Generated by Django 4.0.4 on 2024-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='elevator_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
